### ISSUE TITLE
The detection results on rviz are very stuck

### ISSUE THREAD

**Issue by 504115681** [ethz-asl/dynablox#16] opened 2023-08-31 03:36 UTC
Thank you for open sourcing this excellent work!
When I use the Velodyne16 lidar data in gazebo to test the algorithm, the detection results on rviz are very stuck, as shown in the video below:

https://github.com/ethz-asl/dynablox/assets/55040440/9e55e986-3820-4e57-bc50-7767bc61212a

In addition, the terminal keeps printing (I ignore it for now):

> Failed to find match for field 't'.
> Failed to find match for field 'reflectivity'.
> Failed to find match for field 'ambient'.
> Failed to find match for field 'range'.

Some changes are as follows:
1. Modify the lidar hardware parameters in "default.yaml":

>    # sensor_horizontal_resolution: 2048
>    # sensor_vertical_resolution: 64
>    # sensor_vertical_field_of_view_degrees: 33.22222
>    sensor_horizontal_resolution: 720
>    sensor_vertical_resolution: 16
>    sensor_vertical_field_of_view_degrees: 30

2. Modified the lidar topic and tf in "play_doals_data.launch".

>      
> 
>      <remap from="pointcloud" to="/velodyne_points" />
>      <remap from="~pointcloud_corrected" to="/pointcloud" />
>      <param name="odom_frame_id" value="odom" />
>      <param name="lidar_frame_id" value="velodyne" />

What else do I need to modify? I would be grateful for any help!

**Comment by 504115681** [comment] 2023-08-31 13:25
The CPU of my computer is i7-10750H, which is about the same performance as AMD-4800U. I downloaded the small_town_simulation sequence in DOASL for testing, but it is still stuck. The results are as follows:


https://github.com/ethz-asl/dynablox/assets/55040440/13714770-7816-40a1-b84f-3e75f7c3fcba

**Comment by 504115681** [comment] 2023-08-31 13:40
I downloaded hauptgebaeude_sequence_1 in DOASL for testing. This sequence performed very smoothly without any lag, which is so strange! The video is as follows:

https://github.com/ethz-asl/dynablox/assets/55040440/4cc09052-9b37-43af-b7fd-69e42edf6263

**Comment by Schmluk** [comment] 2023-09-05 17:11
Hi @504115681 
Many thanks for your interest! That is very strange, we haven't really had problems being 'stuck'. Few pointers that may hoepfully help you resolve your issues:
- The visualization (including the entire point cloud) is published after a frame is processed, so if no new visualizations appear the system is still processing or waiting to process the next frame.
- Some irregularities can arise if the max integration distance is not set and a very large extent pointcloud is received, as the entire volume will be integrated before moving to the next frame. This can be expensive and take some time (see computation time results for fixed and open max integration range in the paper)
- It could also be related to the tf's not being received, as the system waits for the transform of the pointlcouds to arrive.
- In the past I had issues with ROS subscribers getting slow for long queue sizes, in your videos you can see the small time lag of the published (most recent processed) pose by dynablox and the simulated robot pose, indicating that not all frames are being processed in real-time. However, this lag was usually negligible in our experiments.

W.r.t. `Failed to find match for field 't'`: This is printed by the lidar undistortion, not by dynablox, and is not an issue (unless you need the cloud to have these fields later)

**Comment by 504115681** [comment] 2023-09-07 01:45
> Hi @504115681 Many thanks for your interest! That is very strange, we haven't really had problems being 'stuck'. Few pointers that may hoepfully help you resolve your issues:
> 
> * The visualization (including the entire point cloud) is published after a frame is processed, so if no new visualizations appear the system is still processing or waiting to process the next frame.
> * Some irregularities can arise if the max integration distance is not set and a very large extent pointcloud is received, as the entire volume will be integrated before moving to the next frame. This can be expensive and take some time (see computation time results for fixed and open max integration range in the paper)
> * It could also be related to the tf's not being received, as the system waits for the transform of the pointlcouds to arrive.
> * In the past I had issues with ROS subscribers getting slow for long queue sizes, in your videos you can see the small time lag of the published (most recent processed) pose by dynablox and the simulated robot pose, indicating that not all frames are being processed in real-time. However, this lag was usually negligible in our experiments.
> 
> W.r.t. `Failed to find match for field 't'`: This is printed by the lidar undistortion, not by dynablox, and is not an issue (unless you need the cloud to have these fields later)

Thank you for your help! Its a problem with TF, everything works fine now!

**Closed** 2023-09-07 10:09 UTC

**Comment by JoLichtenfeld** [comment] 2024-02-07 13:47
Hi @504115681 , 
I am experiencing the same issues when running the small_town_simulation sequence. Other DOALS sequences run well.
How did you solve the tf problem?
In my case it seems to be caused by lidar_undistortion with the warning `Waited 2.500s, but still could not get the TF from os1_lidar to map`.
